// <auto-generated />
using CuaHangXeMoHinh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

#nullable disable

namespace CuaHangXeMoHinh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209095459_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thương hiệu điện tử tiêu dùng toàn cầu",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giải pháp chiếu sáng thông minh",
                            Name = "Philips Hue"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thương hiệu điều hòa nổi tiếng",
                            Name = "Daikin"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hãng công nghệ đa quốc gia",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Thiết bị mạng & nhà thông minh",
                            Name = "TP‑Link"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Thiết bị âm thanh & giải trí cao cấp",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Điện tử tiêu dùng & thiết bị gia đình",
                            Name = "LG"
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thiết bị kiểm soát nhiệt độ và chất lượng không khí thông minh.",
                            Name = "Điều hòa, máy sưởi thông minh"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Thiết bị an ninh và bảo mật nhà ở thông minh.",
                            Name = "Camera, khóa cửa thông minh"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thiết bị chiếu sáng và kiểm soát điện năng thông minh.",
                            Name = "Đèn LED, công tắc điều khiển"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thiết bị giải trí đa phương tiện thông minh.",
                            Name = "Loa, TV, hệ thống âm thanh"
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusLogs", (string)null);
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Cost = 8000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7485),
                            Description = "Điều hòa thông minh – 1.5HP, WiFi, tiết kiệm điện",
                            IsPublished = true,
                            Name = "Xiaomi Smart Air Conditioner 1.5HP",
                            Price = 12000000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            CategoryId = 1,
                            Cost = 6000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7490),
                            Description = "Máy sưởi thông minh Daikin, điều chỉnh nhiệt độ tự động",
                            IsPublished = true,
                            Name = "Daikin Smart Heater Panel",
                            Price = 9000000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 7,
                            CategoryId = 1,
                            Cost = 5500000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7494),
                            Description = "Máy sưởi LG 2kW, tiết kiệm năng lượng, có hẹn giờ",
                            IsPublished = true,
                            Name = "LG Smart Heater 2kW",
                            Price = 8000000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 1,
                            Cost = 10000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7498),
                            Description = "Điều hòa Samsung WindFree – làm mát không gió lạnh trực tiếp",
                            IsPublished = true,
                            Name = "Samsung WindFree Smart AC",
                            Price = 15000000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 1,
                            Cost = 4500000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7554),
                            Description = "Máy lọc không khí + điều hòa nhiệt độ thông minh",
                            IsPublished = true,
                            Name = "Xiaomi Smart Air Purifier Pro",
                            Price = 7000000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CategoryId = 2,
                            Cost = 3000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7558),
                            Description = "Khóa cửa vân tay & mã PIN, kết nối app",
                            IsPublished = true,
                            Name = "Xiaomi Smart Door Lock Pro",
                            Price = 4500000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            CategoryId = 2,
                            Cost = 800000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7562),
                            Description = "Camera IP quay 360°, phát hiện chuyển động",
                            IsPublished = true,
                            Name = "TP‑Link Tapo C225 Security Camera",
                            Price = 1200000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            CategoryId = 2,
                            Cost = 3200000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7565),
                            Description = "Khóa cửa thông minh Samsung, mở khóa từ xa",
                            IsPublished = true,
                            Name = "Samsung Smart Door Lock",
                            Price = 5000000m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            CategoryId = 2,
                            Cost = 900000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7568),
                            Description = "Camera an ninh 2K, ghi hình ban đêm",
                            IsPublished = true,
                            Name = "Xiaomi Security Camera 2K",
                            Price = 1500000m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            CategoryId = 2,
                            Cost = 150000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7572),
                            Description = "Cảm biến mở cửa thông minh, kết nối app",
                            IsPublished = true,
                            Name = "TP‑Link Smart Door Sensor",
                            Price = 300000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CategoryId = 3,
                            Cost = 300000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7575),
                            Description = "Bóng đèn LED đổi màu, điều chỉnh sáng qua app",
                            IsPublished = true,
                            Name = "Philips Hue White & Color LED Bulb",
                            Price = 500000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 5,
                            CategoryId = 3,
                            Cost = 250000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7580),
                            Description = "Công tắc thông minh điều khiển từ xa",
                            IsPublished = true,
                            Name = "TP‑Link Smart Light Switch",
                            Price = 400000m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            CategoryId = 3,
                            Cost = 200000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7584),
                            Description = "Đèn LED dải thông minh, đổi màu, hẹn giờ",
                            IsPublished = true,
                            Name = "Xiaomi Smart LED Strip 5m",
                            Price = 350000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 2,
                            CategoryId = 3,
                            Cost = 800000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7597),
                            Description = "Panel LED trần thông minh, điều chỉnh độ sáng",
                            IsPublished = true,
                            Name = "Philips Hue LED Panel",
                            Price = 1200000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            CategoryId = 3,
                            Cost = 100000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7611),
                            Description = "Ổ cắm thông minh, điều khiển từ xa",
                            IsPublished = true,
                            Name = "TP‑Link Smart Plug Socket",
                            Price = 200000m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 6,
                            CategoryId = 4,
                            Cost = 4000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7614),
                            Description = "Soundbar đa kênh, kết nối Bluetooth & WiFi",
                            IsPublished = true,
                            Name = "Sony Smart Soundbar 5.1",
                            Price = 6000000m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            CategoryId = 4,
                            Cost = 10000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7618),
                            Description = "Smart TV 4K, ứng dụng Android, điều khiển từ xa",
                            IsPublished = true,
                            Name = "Samsung 55\" Smart TV 4K",
                            Price = 15000000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 7,
                            CategoryId = 4,
                            Cost = 12000000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7621),
                            Description = "TV OLED, HDR, WebOS, kết nối Internet",
                            IsPublished = true,
                            Name = "LG OLED Smart TV 48\"",
                            Price = 18000000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 1,
                            CategoryId = 4,
                            Cost = 800000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7625),
                            Description = "Loa thông minh, hỗ trợ điều khiển giọng nói",
                            IsPublished = true,
                            Name = "Xiaomi Mi Smart Speaker",
                            Price = 1200000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 5,
                            CategoryId = 4,
                            Cost = 500000m,
                            CreatedAt = new DateTime(2025, 12, 9, 9, 54, 56, 834, DateTimeKind.Utc).AddTicks(7628),
                            Description = "TV Box Android, biến TV thường thành Smart TV",
                            IsPublished = true,
                            Name = "TP‑Link Smart TV Box",
                            Price = 800000m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrimary = true,
                            ProductId = 1,
                            Url = "/images/aircon1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsPrimary = true,
                            ProductId = 2,
                            Url = "/images/heater1.jpg"
                        },
                        new
                        {
                            Id = 3,
                            IsPrimary = true,
                            ProductId = 3,
                            Url = "/images/heater2.jpg"
                        },
                        new
                        {
                            Id = 4,
                            IsPrimary = true,
                            ProductId = 4,
                            Url = "/images/aircon2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsPrimary = true,
                            ProductId = 5,
                            Url = "/images/airpurifier.jpg"
                        },
                        new
                        {
                            Id = 6,
                            IsPrimary = true,
                            ProductId = 6,
                            Url = "/images/doorlock1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            IsPrimary = true,
                            ProductId = 7,
                            Url = "/images/camera1.jpg"
                        },
                        new
                        {
                            Id = 8,
                            IsPrimary = true,
                            ProductId = 8,
                            Url = "/images/doorlock2.jpg"
                        },
                        new
                        {
                            Id = 9,
                            IsPrimary = true,
                            ProductId = 9,
                            Url = "/images/camera2.jpg"
                        },
                        new
                        {
                            Id = 10,
                            IsPrimary = true,
                            ProductId = 10,
                            Url = "/images/doorsensor.jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsPrimary = true,
                            ProductId = 11,
                            Url = "/images/ledbulb1.jpg"
                        },
                        new
                        {
                            Id = 12,
                            IsPrimary = true,
                            ProductId = 12,
                            Url = "/images/switch1.jpg"
                        },
                        new
                        {
                            Id = 13,
                            IsPrimary = true,
                            ProductId = 13,
                            Url = "/images/ledstrip1.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsPrimary = true,
                            ProductId = 14,
                            Url = "/images/ledpanel1.jpg"
                        },
                        new
                        {
                            Id = 15,
                            IsPrimary = true,
                            ProductId = 15,
                            Url = "/images/plug1.jpg"
                        },
                        new
                        {
                            Id = 16,
                            IsPrimary = true,
                            ProductId = 16,
                            Url = "/images/soundbar1.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsPrimary = true,
                            ProductId = 17,
                            Url = "/images/tv_samsung55.jpg"
                        },
                        new
                        {
                            Id = 18,
                            IsPrimary = true,
                            ProductId = 18,
                            Url = "/images/tv_lg48.jpg"
                        },
                        new
                        {
                            Id = 19,
                            IsPrimary = true,
                            ProductId = 19,
                            Url = "/images/speaker1.jpg"
                        },
                        new
                        {
                            Id = 20,
                            IsPrimary = true,
                            ProductId = 20,
                            Url = "/images/tvbox1.jpg"
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Address", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Order", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.HasOne("CuaHangXeMoHinh.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderItem", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderStatusLog", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Order", "Order")
                        .WithMany("StatusLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Product", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.ProductImage", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Review", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
