// <auto-generated />
using System;
using CuaHangXeMoHinh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangXeMoHinh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Huyền thoại ngựa chồm từ Maranello, Ý.",
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Biểu tượng bò tót hung dữ, thiết kế góc cạnh.",
                            Name = "Lamborghini"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sự chính xác và hoàn hảo từ cơ khí Đức.",
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Công nghệ đường đua F1 áp dụng cho siêu xe đường phố.",
                            Name = "McLaren"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Đỉnh cao của tốc độ và sự xa xỉ tột bậc.",
                            Name = "Bugatti"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sức mạnh Mỹ với dòng Mustang huyền thoại.",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Hiệu suất cao kết hợp sự sang trọng tuyệt đối.",
                            Name = "Mercedes-AMG"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Hiệu suất cao kết hợp sự sang trọng tuyệt đối.",
                            Name = "Rolls-Royce "
                        },
                        new
                        {
                            Id = 9,
                            Description = "Chevrolet.",
                            Name = "Chevrolet "
                        },
                        new
                        {
                            Id = 10,
                            Description = "Koenigsegg .",
                            Name = "Koenigsegg  "
                        },
                        new
                        {
                            Id = 11,
                            Description = "Pagani",
                            Name = "Pagani"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cadillac.",
                            Name = "Cadillac "
                        },
                        new
                        {
                            Id = 13,
                            Description = "Dodge .",
                            Name = "Dodge  "
                        },
                        new
                        {
                            Id = 14,
                            Description = "Aston Martin",
                            Name = "Aston Martin"
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Siêu xe thể thao hiệu suất cao, thiết kế khí động học.",
                            Name = "Supercars"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Những mẫu xe cổ điển mang vẻ đẹp vượt thời gian.",
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sức mạnh cơ bắp Mỹ thuần túy, động cơ V8 gầm rú.",
                            Name = "Muscle"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xe đua chuyên nghiệp từ các giải đấu danh giá.",
                            Name = "Racing (GT/F1)"
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusLogs", (string)null);
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            CategoryId = 1,
                            Cost = 299000m,
                            CreatedAt = new DateTime(2026, 2, 4, 12, 20, 50, 582, DateTimeKind.Utc).AddTicks(2665),
                            Description = "Mô hình siêu xe Mclaren 720s\r\n\r\nTỉ Lệ: 1:32\r\n\r\nKích thước: Dài 15.5cm; rộng 5cm; cao 4cm\r\n\r\nChức năng: Có đèn, điện trước và sau khi mở cửa; mở được 2 cửa cánh gió; xe có trớn để chạy được.\r\n\r\nChất Liệu: Đối với xe ô tô toàn bộ khung xe được làm đúc bằng nhựa resin hoặc hợp kim nguyên khối, nội thất xe làm bằng nhựa ABS , lốp xe được làm từ cao su tự nhiên, các chi tiết ống xả được mạ crôm , lưới tản nhiệt bằng kim loại\r\n\r\nĐược sơn bằng tĩnh điện cho nước sơn sáng bóng, mỏng, bền. vì này là hàng cao cấp nên được sơn nhiều lớp theo tiêu chuẩn của nhà sản xuất.",
                            IsPublished = true,
                            Name = "McLaren 720s",
                            Price = 189000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 10,
                            CategoryId = 1,
                            Cost = 289000m,
                            CreatedAt = new DateTime(2026, 2, 4, 12, 20, 50, 582, DateTimeKind.Utc).AddTicks(2669),
                            Description = "Thông tin sản phẩm Mô hình xe Koenigsegg Jesko tỉ lệ 1:32 kèm đế trưng bày\r\n\r\nTỉ lệ: 1:32 (nhỏ hơn xe thật 32 lần)\r\n\r\nMàu: Màu cam,trắng,đen\r\n\r\nKích thước: Dài x Rộng x Cao (15 x 6,5 x 4,5 cm)\r\n\r\nKhối lượng: ~300gr\r\n\r\nChất liệu: Toàn bộ phần thân vỏ được làm bằng kim loại nguyên khối với nước sơn tĩnh điện 3 lớp cực đẹp, Gầm xe và nội thất bằng nhựa, bánh xe bằng cao su cao cấp\r\n\r\nTính năng:\r\n\r\n️ Mở 2 cửa, capo và cốp\r\n\r\n️ Có đèn âm thanh và trớn\r\n\r\nMục đích sử dụng:\r\n\r\n️ Sưu tầm xe mô hình\r\n\r\n️ Trang trí, nội thất\r\n\r\n️ Quà tặng cho bạn nam, quà tặng cho bé trai, quà noel, quà sinh nhật",
                            IsPublished = true,
                            Name = "Koenigsegg Jesko ",
                            Price = 189000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 12,
                            CategoryId = 2,
                            Cost = 299000m,
                            CreatedAt = new DateTime(2026, 2, 4, 12, 20, 50, 582, DateTimeKind.Utc).AddTicks(2671),
                            Description = "🏎️ Mô Hình Cadillac Eldorado Biarritz Classic 1:32 (Hợp Kim)\r\nChất liệu: Hợp kim Diecast siêu bền, lốp cao su, nội thất ABS.\r\n\r\nKích thước: ~15.5 x 7 x 4 cm.\r\n\r\nChức năng:\r\n\r\nMở toàn bộ cửa (cánh chim), nắp máy trước/sau.\r\n\r\nPhun khói: Có hệ thống phun sương giả lập khói từ ống xả (châm nước).\r\n\r\nĐèn & Âm thanh: Đèn LED trước/sau + tiếng động cơ gầm rú.\r\n\r\nVận hành: Có cót lùi (Pull-back) và giảm xóc 4 bánh.\r\n\r\nMục đích: Quà tặng, sưu tầm, decor bàn làm việc.",
                            IsPublished = true,
                            Name = "Cadillac Eldorado Biarritz Classic  ",
                            Price = 199000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 13,
                            CategoryId = 3,
                            Cost = 299000m,
                            CreatedAt = new DateTime(2026, 2, 4, 12, 20, 50, 582, DateTimeKind.Utc).AddTicks(2674),
                            Description = "🏎️ Mô Hình Dodge Challenger SRT Hellcat Redeye V8 1:32 (Hợp Kim)\r\nChất liệu: Hợp kim Diecast siêu bền, lốp cao su, nội thất ABS.\r\n\r\nKích thước: ~15.5 x 7 x 4 cm.\r\n\r\nChức năng:\r\n\r\nMở toàn bộ cửa (cánh chim), nắp máy trước/sau.\r\n\r\nPhun khói: Có hệ thống phun sương giả lập khói từ ống xả (châm nước).\r\n\r\nĐèn & Âm thanh: Đèn LED trước/sau + tiếng động cơ gầm rú.\r\n\r\nVận hành: Có cót lùi (Pull-back) và giảm xóc 4 bánh.\r\n\r\nMục đích: Quà tặng, sưu tầm, decor bàn làm việc.",
                            IsPublished = true,
                            Name = "Dodge Challenger SRT Hellcat Redeye V8 ",
                            Price = 199000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 14,
                            CategoryId = 4,
                            Cost = 299000m,
                            CreatedAt = new DateTime(2026, 2, 4, 12, 20, 50, 582, DateTimeKind.Utc).AddTicks(2676),
                            Description = "🏎️ Mô Hình  Aston Martin Redbull F1V8 1:42 (Hợp Kim)\r\nChất liệu: Hợp kim Diecast siêu bền, lốp cao su, nội thất ABS.\r\n\r\nKích thước: ~15.5 x 7 x 4 cm.\r\n\r\nChức năng:\r\n\r\nMở toàn bộ cửa (cánh chim), nắp máy trước/sau.\r\n\r\nPhun khói: Có hệ thống phun sương giả lập khói từ ống xả (châm nước).\r\n\r\nĐèn & Âm thanh: Đèn LED trước/sau + tiếng động cơ gầm rú.\r\n\r\nVận hành: Có cót lùi (Pull-back) và giảm xóc 4 bánh.\r\n\r\nMục đích: Quà tặng, sưu tầm, decor bàn làm việc.",
                            IsPublished = true,
                            Name = " Aston Martin Redbull F1 ",
                            Price = 199000m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrimary = true,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/main.png"
                        },
                        new
                        {
                            Id = 2,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/1.png"
                        },
                        new
                        {
                            Id = 3,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/2.png"
                        },
                        new
                        {
                            Id = 4,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/3.png"
                        },
                        new
                        {
                            Id = 5,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/4.png"
                        },
                        new
                        {
                            Id = 6,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/5.png"
                        },
                        new
                        {
                            Id = 7,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "/images/MClaren_720s/6.png"
                        },
                        new
                        {
                            Id = 8,
                            IsPrimary = true,
                            ProductId = 2,
                            Url = "/images/Koenigsegg_Jesko/main.png"
                        },
                        new
                        {
                            Id = 9,
                            IsPrimary = false,
                            ProductId = 2,
                            Url = "/images/Koenigsegg_Jesko/1.png"
                        },
                        new
                        {
                            Id = 10,
                            IsPrimary = false,
                            ProductId = 2,
                            Url = "/images/Koenigsegg_Jesko/2.png"
                        },
                        new
                        {
                            Id = 11,
                            IsPrimary = false,
                            ProductId = 2,
                            Url = "/images/Koenigsegg_Jesko/3.png"
                        },
                        new
                        {
                            Id = 12,
                            IsPrimary = true,
                            ProductId = 3,
                            Url = "/images/Cadillac_Eldorado_Biarritz_Classic/main.png"
                        },
                        new
                        {
                            Id = 13,
                            IsPrimary = false,
                            ProductId = 3,
                            Url = "/images/Cadillac_Eldorado_Biarritz_Classic/1.png"
                        },
                        new
                        {
                            Id = 14,
                            IsPrimary = false,
                            ProductId = 3,
                            Url = "/images/Cadillac_Eldorado_Biarritz_Classic/2.png"
                        },
                        new
                        {
                            Id = 15,
                            IsPrimary = true,
                            ProductId = 4,
                            Url = "/images/Dodge_challenger/main.png"
                        },
                        new
                        {
                            Id = 16,
                            IsPrimary = false,
                            ProductId = 4,
                            Url = "/images/Dodge_challenger/1.png"
                        },
                        new
                        {
                            Id = 17,
                            IsPrimary = false,
                            ProductId = 4,
                            Url = "/images/Dodge_challenger/2.png"
                        },
                        new
                        {
                            Id = 18,
                            IsPrimary = true,
                            ProductId = 5,
                            Url = "/images/AstonMartin_rebullf1/main.png"
                        },
                        new
                        {
                            Id = 19,
                            IsPrimary = false,
                            ProductId = 5,
                            Url = "/images/AstonMartin_rebullf1/1.png"
                        },
                        new
                        {
                            Id = 20,
                            IsPrimary = false,
                            ProductId = 5,
                            Url = "/images/AstonMartin_rebullf1/2.png"
                        },
                        new
                        {
                            Id = 21,
                            IsPrimary = false,
                            ProductId = 5,
                            Url = "/images/AstonMartin_rebullf1/3.png"
                        });
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Address", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Order", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.HasOne("CuaHangXeMoHinh.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderItem", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.OrderStatusLog", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Order", "Order")
                        .WithMany("StatusLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Product", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.ProductImage", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Review", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CuaHangXeMoHinh.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CuaHangXeMoHinh.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
